source 'https://rubygems.org'
#Inside of server.rb
require 'sinatra'
require 'pry'
require 'sinatra/contrib'
require 'sinatra/reloader'

# We're going to need to require our class files
require_relative('lib/sinatra_todo.rb')
